example_path: data/MATH/test_split.jsonl

output_path: results/instruct_pass_8.jsonl

model_path: models/Qwen2.5-Math-1.5B-Instruct

max_tokens: 4096

temperature: 0.7

top_p: 0.95

max_samples: 5000

pass_k: 8

