example_path: "data/MATH/math500-test.jsonl"

prompt_path: "prompts/r1_zero_replace_space_with_lf.prompt"

output_path: "results/sft_prompt_tuned_math500_pass_64.jsonl"

model_path: "checkpoints/sft_v4_prompt_tuning/epoch0"

max_tokens: 4096

temperature: 0.7

top_p: 0.95

max_samples: 500

pass_k: 64
