# 数据集路径
example_path: "data/gsm8k/test_clean.jsonl"

# Prompt 模板路径
prompt_path: "prompts/r1_zero.prompt"

# 结果保存路径
output_path: "results/grpo_no_std_norm/grpo_no_std_norm_gsm8k_pass1.jsonl"

model_path: "checkpoints/grpo_no_std_norm_5e-6/checkpoint-step-450"

max_tokens: 2048

temperature: 0

top_p: 0.95

max_samples: 0

pass_k: 1