# test_pipeline.yaml
project_name: "CS336_test_pipeline"

paths:
  input_dir: "data/crawls/wet"
  base_output_dir: "data/test_pipeline"

pipeline:
  resume: True

models:
  quality_classifier: "data/my_classifiers/best_classifier.bin"
  toxic_path: "data/classifiers/jigsaw_fasttext_bigrams_hatespeech_final.bin"
  nsfw_path: "data/classifiers/jigsaw_fasttext_bigrams_nsfw_final.bin"
  lang_path: "data/classifiers/lid.176.bin"
  label_mapping:
    __label__low_quality: 'cc'
    __label__high_quality: 'wiki'

processing:
  max_workers: 15
  max_files_limit: 30
  worker_ttl: 20

filter:
  min_doc_length: 200       # 放宽长度限制
  language:
    target: "en"
    min_score: 0.9         # 允许混杂一些非标准英语
  safety:
    nsfw_threshold: 0.02      # 宽松的安全阈值
    toxic_threshold: 0.02
  
deduplication:
  fuzzy:
    n_gram: 13
    num_hashes: 128
    bands: 32
    threshold: 0.8