# configs/grop_config.yaml

model:
  model_path: "checkpoints/sft_v4/epoch0"
  best_reward: 0
  start_step: 0
  dtype: "bfloat16"
  # attn_implementation: "flash_attention_2"
  attn_implementation: "sdpa"
  trust_remote_code: true
  wandb_id: null

runtime:
  device: "cuda"
  cuda_visible_devices: null
  hf_device_map: null
  max_memory_gb_per_gpu: null
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.25

data:
  train_path: "data/CoT/Bespoke-Stratos-17k-R1-tag.jsonl"
  valid_path: "data/MATH/test_split.jsonl"
  prompt_path: "prompts/r1_zero.prompt"
  max_seq_length: 4096
  max_samples: 5000
  start_sample: 3609

training:
  output_dir: "checkpoints/drgrpo_test"
  n_grpo_steps: 500
  warmup_ratio: 0.1
  learning_rate: 5.0e-6
  advantage_eps: 1.0e-6
  rollout_batch_size: 64
  inference_batch_size: 2
  group_size: 8
  sampling_temperature: 1.0
  repetition_penalty: 1.0
  sampling_min_tokens: 4
  sampling_max_tokens: 4096
  epochs_per_rollout_batch: 1
  save_steps: 50

  micro_batch_size: 1
  gradient_checkpointing: True
  loss_type: "grpo_clip"
  clip_range: 0.2
  max_grad_norm: 1.0

  # drgrpo配置，移除std标准化，移除响应长度归一化，转而采用固定长度归一化
  normalize_by_std: False
  remove_length_norm: True

  length_panelty: True

  # === vllm 参数 ===
  enforce_eager: True
  enable_prefix_caching: False
  stop_tokens: ["</answer>"]

  fixed_norm_length: 2048

evaluation:
  eval_every_steps: 10
  num_examples_to_log: 4
  max_new_tokens: 4096

wandb:
  project: "CS336-Assignment5-Alignment"
  run_name: "drgrpo_test"
  entity: null
