# 数据集路径
example_path: "data/MATH/validation.jsonl"

# Prompt 模板路径
prompt_path: "cs336_alignment/prompts/r1_zero.prompt"

# 结果保存路径
output_path: "results/sft_v6_epoch0_result.jsonl"

# 模型路径 (可以是本地路径或 HuggingFace ID)
model_path: "checkpoints/sft_v6_no_resize_warmup/epoch0"

max_tokens: 4096

temperature: 0.65