# configs/sft_config.yaml
model:
  model_path: "models/Qwen2.5-Math-1.5B"
  dtype: "bfloat16"
  # attn_implementation: "flash_attention_2"
  attn_implementation: "sdpa"

data:
  train_path: "data/MATH/sft_v3.jsonl"
  valid_path: "data/MATH/validation.jsonl"
  prompt_path: "cs336_alignment/prompts/r1_zero.prompt"
  max_seq_length: 4096
  max_samples: null

training:
  output_dir: "checkpoints/sft_v3"
  learning_rate: 1.0e-5
  epochs: 4

  micro_batch_size: 4
  gradient_accumulation_steps: 16
  
  max_grad_norm: 1.0
  save_steps: 1000  # 或者设大一点只存最后

evaluation:
  eval_every_steps: 10
  num_examples_to_log: 4
  max_new_tokens: 4096

wandb:
  project: "CS336-Assignment5-Alignment"
  run_name: "sft-qwen-1.5b-v3-epoch1"
  entity: null 