example_path: "data/MATH/test_split.jsonl"

prompt_path: "prompts/r1_zero.prompt"

output_path: "results/drgrpo_v6_step_350_pass_8.jsonl"

model_path: "checkpoints/drgrpo_5e-6/checkpoint-step-350"

max_tokens: 4096

temperature: 0.7

top_p: 0.95

max_samples: 5000

pass_k: 8
